# Generated by Django 2.2.5 on 2019-12-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('literature_id', models.SlugField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('report_number', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=256)),
                ('detail', models.CharField(max_length=256)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('abstract', models.TextField()),
                ('journal_ref', models.TextField()),
            ],
        ),
    ]
